# CONFIG_GCC_PLUGIN_LATENT_ENTROPY is not set
# CONFIG_RANDSTRUCT_FULL is not set
# CONFIG_RANDSTRUCT_PERFORMANCE is not set
CONFIG_DEBUG_INFO_DWARF5=y
# CONFIG_DEBUG_INFO_NONE is not set
# CONFIG_GCC_PLUGINS is not set
CONFIG_READABLE_ASM=y
CONFIG_VMLINUX_MAP=y
CONFIG_DEBUG_INFO=y
# CONFIG_DEBUG_INFO_BTF is not set
CONFIG_DEBUG_INFO_COMPRESSED_NONE=y
# CONFIG_DEBUG_INFO_COMPRESSED_ZLIB is not set
# CONFIG_DEBUG_INFO_REDUCED is not set
# CONFIG_DEBUG_INFO_SPLIT is not set
CONFIG_GDB_SCRIPTS=y
CONFIG_PAHOLE_HAS_LANG_EXCLUDE=y
CONFIG_PAHOLE_HAS_SPLIT_BTF=y
